### ISSUE TITLE
Lessphp example

### ISSUE THREAD

**Issue by Woutwo** [yayscripting/YAY-Scripting-framework#3]
Simple example of Lessphp, and makes the whole site just a little bit better.

``` css
.rounded-corners(@radius: 5px) {
    border-radius: @radius;
    -webkit-border-radius: @radius;
    -moz-border-radius: @radius;
}

.box-shadow(@x; @y; @spread; @color) {
    box-shadow: @x @y @spread @color;
    -webkit-box-shadow: @x @y @spread @color;
    -moz-box-shadow: @x @y @spread @color;
}

@width: 500px;

body{
    background: #eee;

    #container{     
        width: @width;
        padding: 30px;
        margin: 100px auto 0 auto;
        background: white;

        border: 1px #444 solid;
        .rounded-corners();
        .box-shadow(0px; 3px; 5px; #777);

        form{
            padding: 20px;
        }
    }
}
```
